version = 1

[[analyzers]]
name = "go"
enabled = true

  [analyzers.meta]
  import_root = "github.com/jlk/webapp-base"

[[analyzers]]
name = "javascript"
enabled = true

  [analyzers.meta]
  plugins = ["react"]
  style_guide = "standard"
  dialect = "typescript"
  environment = ["nodejs"]
